#!/usr/bin/env bash

. $(dirname $0)/func.sh

TEST=$1

if [[ -z ${TEST} ]]; then
    TEST="back/tests/"
    else
    TEST="back/tests/${TEST}"
fi

php_container back/tests/utils/phpunit --bootstrap back/tests/utils/autoload.php ${TEST}
