#!/usr/bin/env bash

. $(dirname $0)/func.sh

php_container back/tests/utils/phpab -o back/tests/utils/autoload.php back/src back/tests/utils
php_container back/tests/utils/phpunit --bootstrap back/tests/utils/autoload.php back/tests/*
